"use client";
import { Box, Grid, List, ThemeProvider, createTheme } from "@mui/material";
import "./globals.css";
import { Inter } from "next/font/google";

import SidNav from "./SidNavbar/index";
import Divider from "@mui/material/Divider";
import Toolbar from "@mui/material/Toolbar";
import IconButton from "@mui/material/IconButton";
import ChevronLeftIcon from "@mui/icons-material/ChevronLeft";
import {
  mainListItems,
  secondaryListItems,
} from "./TemplateMui/Deshboard/ListItem";
import HeaderPage from "./TemplateMui/header";
import { theme } from "./ThemingContainet/createTheme";
import NavHeader from "./SidNavbar/NavHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body className={inter.className}>
          <Grid container>
            <Grid lg={2.2} xl={2.2} sm={2.2} xs={2.2}>
              <SidNav></SidNav>
            </Grid>

            <Grid lg={9.8} xl={9.8} sm={9.8} xs={9.8}>
              <HeaderPage></HeaderPage>
              <Box
                sx={{
                  paddingRight: 6,
                  paddingLeft: 6,
                  marginTop: 10,
                  marginBottom: 10,
                }}
              >
                {children}
              </Box>
            </Grid>
          </Grid>
        </body>
      </ThemeProvider>
    </html>
  );
}
